title: Cheyanne Shariat
email: cshariat@caltech.edu
description: >-
 Hello! Welcome to my academic website.
baseurl: "" # leave this empty for GitHub Pages
url: "https://cheyanneshariat.github.io"

theme: null
sass:
  style: compressed

# Tell Jekyll where to find your CSS
include:
  - assets

# Custom Minima setup
minima:
  skin: custom-dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - cv.md
  - contact.md
