title: Cheyanne Shariat
email: cshariat@caltech.edu
description: >-
 Hello! Welcome to my academic website.
baseurl: "" # leave this empty for GitHub Pages
url: "https://cheyanneshariat.github.io"

theme: minima
minima:
  skin: custom-dark
sass:
  style: compressed

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
